export const CONFIG = {
  TEST_MODE: true,
  VIRTUAL_BALANCE_USD: 100,

  DEFAULT_BUY_SOL: 0.001,
  SLIPPAGE_BPS: 500,

  TAKE_PROFIT_PERCENT: 50,
  STOP_LOSS_PERCENT: 30,

  PRIORITY_FEE_LAMPORTS: 200000
};